<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <LangVersion>10</LangVersion>
    <PackageId>Digitalroot.Valheim.Modding.Framework</PackageId>
    <RootNamespace>Digitalroot.Modding.Framework</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <Copyright>Copyright © Digitalroot Technologies 2021 - 2026</Copyright>
    <PackageProjectUrl>https://github.com/Digitalroot-Valheim/DMF</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Digitalroot-Valheim/DMF</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>ValheimRcon_color.png</PackageIcon>
    <PackageIconUrl />
    <PackageTags>valheim, digitalroot</PackageTags>
    <Authors>Digitalroot</Authors>
    <Company>Digitalroot Technologies</Company>
    <Product>Digitalroot Modding Framework</Product>
    <Description>Digitalroot Modding Framework for Valheim</Description>
    <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
    <ApplicationIcon>ValheimRcon_black.ico</ApplicationIcon>
    <IsPublishable>False</IsPublishable>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <NeutralLanguage>en-US</NeutralLanguage>
    <VersionPrefix>0.0.1</VersionPrefix>
    <RestoreAdditionalProjectSources>
      https://nuget.bepinex.dev/v3/index.json;
      https://digitalroot-valheim-nuget.s3.us-west-2.amazonaws.com/index.json
    </RestoreAdditionalProjectSources>
    <Title>Digitalroot Valheim Modding Framework</Title>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Common\Config\AbstractConfigProvider.cs.bak" />
    <Compile Include="Common\Config\ConfigEntryBaseExtension.cs.bak" />
    <Compile Include="Common\Config\ConfigFileExtension.cs.bak" />
    <Compile Include="Common\Config\ConfigProviderFactory.cs.bak" />
    <Compile Include="Common\Config\ConfigProviderSettings.cs.bak" />
    <Compile Include="Common\Config\ConfigProviderType.cs.bak" />
    <Compile Include="Common\Config\Providers\AbstractProxyCustomSyncedValue.cs.bak" />
    <Compile Include="Common\Config\Providers\BepInEx\AbstractBepInExConfigProvider.cs.bak" />
    <Compile Include="Common\Config\Providers\BepInEx\BepInExFileBasedConfigProvider.cs.bak" />
    <Compile Include="Common\Config\Providers\BepInEx\BepInExInMemoryBasedConfigProvider.cs.bak" />
    <Compile Include="Common\Config\Providers\JvL\JvLConfigProvider.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSyncConfigProvider.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\ConfigSync.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\CustomSyncedValue.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\CustomSyncedValueBase.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\OwnConfigEntryBase.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\ServerSyncProxyCustomSyncedValue.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\SyncedConfigEntry.cs.bak" />
    <Compile Include="Common\Config\Providers\ServerSync\VersionCheck.cs.bak" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ico\ValheimRcon_color.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="build\Digitalroot.Valheim.Modding.Framework.props">
      <Pack>True</Pack>
      <PackagePath>build\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="[5.4.21]">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Digitalroot.References.Unity" Version="6000.0.75" />
    <PackageReference Include="Digitalroot.Valheim.Common.References" Version="1.0.16" />
    <PackageReference Include="Digitalroot.Valheim.References.JvL" Version="2.30.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>