<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <LangVersion>10</LangVersion>
    <PackageId>Digitalroot.Modding.Framework</PackageId>
    <RootNamespace>Digitalroot.Modding.Framework</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <Copyright>Copyright © Digitalroot Technologies 2021 - 2026</Copyright>
    <PackageProjectUrl>https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.Common.Json</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.Common.Json</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>ValheimRcon_black.png</PackageIcon>
    <PackageIconUrl />
    <PackageTags>valheim, digitalroot</PackageTags>
    <Authors>Digitalroot</Authors>
    <Company>Digitalroot Technologies</Company>
    <Product>Digitalroot Modding Framework</Product>
    <Description>Digitalroot Modding Framework for Valheim</Description>
    <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
    <ApplicationIcon>ValheimRcon_black.ico</ApplicationIcon>
    <IsPublishable>False</IsPublishable>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <NeutralLanguage>en-US</NeutralLanguage>
    <VersionPrefix>0.0.1</VersionPrefix>
    <RestoreAdditionalProjectSources>
      https://nuget.bepinex.dev/v3/index.json;
      https://digitalroot-valheim-nuget.s3.us-west-2.amazonaws.com/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\ico\ValheimRcon_black.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="[5.4.21]">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Digitalroot.References.Unity" Version="6000.0.75" />
    <PackageReference Include="Digitalroot.Valheim.Common.References" Version="1.0.12">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Digitalroot.Valheim.References.JvL" Version="2.30.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Names\SpawnThatMod\" />
  </ItemGroup>

</Project>